# Action Cable uses Redis by default to administer connections, channels, and sending/receiving mensajes over the WebSocket.
production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"] %>

development:
  adapter: async

test:
  adapter: async
